# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-API-More
version:      0.05
version_from: lib/SWISH/API/More.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0.22
    Class::Inspector:              0.01
    Class::ISA:                    0.01
    Data::Dump:                    1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
