--- #YAML:1.0
name:               SWISH-API-More
version:            0.07
abstract:           do more with the SWISH::API
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0.22
    Class::Inspector:     0.01
    Class::ISA:           0.01
    Data::Dump:           1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
